name: "Application Check"

on:
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  php-actions:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: src

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Cache composer dependencies
      uses: actions/cache@v4
      with:
        path: src/vendor
        key: composer-${{ hashFiles('src/composer.lock') }}
        restore-keys: |
          composer-

    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: "8.0"
        tools: composer

    - name: Install Composer dependencies
      run: composer install --no-interaction --prefer-dist --no-progress

    - name: Run PHP Unit Tests suite
      run: composer tests

    - name: Run PHP Stan suit
      run: composer phpstan

    - name: Run PHP Code Sniffer suit
      run: composer phpcs
